### ISSUE TITLE
Create templates

### ISSUE THREAD

**Issue by starsplatter** [code4lib/2016.code4lib.org#12]

**Comment by queryluke** [comment]
I'll give this a shot

**Comment by queryluke** [comment]
Ok, I've kinda got this working on my clone, but the prototype directory has it's own jekyll config file. So when testing this locally, ruby balked at installing jekyll. I had to remove the prototype/docs directory

The other odditiy is that running jekyll creates a new directory _sites which is just a copy of all the files...this is nowhere in the github docs. So, next steps (unless anyone else has experience with this):

I'm going to create a personal repo and do some testing figure out what some of these jekyll configs do. I'll have an update later tonight.

**Comment by queryluke** [comment]
Okay, mostly figured this out. It is possible to have jekyll run on the master branch, but takes some additional configuring. Considering the Github docs don't mention then, my 2cents is that we follow their workflow.

Their workflow is that we continue to commit to the master branch, but to see the changes we'll need to merge the master and gh-pages.

Additionally (another wrench in the system) for the templates to work on your local boxes, you'll need to configure [ruby/bundle/jekyll](https://help.github.com/articles/using-jekyll-with-pages/#installing-jekyll). I.e. pulling the master branch to you local machines won't render the content if you open it as a local file.

So, for the time being, I'm going to make a gh-pages-future branch with the necessary changes. Maybe it's a good time to have a quick hangout to discuss moving forward?

**Comment by sdellis** [comment]
Ok, so this is actually the direction we would need to head anyway since in order to host a GitHub Pages "Project site" (issue #2), we will need to have a gh-pages branch.  

I like the simplicity of Paul Irish's approach in [this article](http://oli.jp/2011/github-pages-workflow/), which is essentially using a post-commit web hook to automatically merge all commits to the master branch to gh-pages.  It needs to be easy and automatic to keep those in sync, and with that approach the only difference then to the normal workflow is `git push --all` instead of `git push` (except for running Jekyll locally to see changes).  Thoughts @roastduckalamode? 

**As for the `prototype` directory, we don't need the docs directory.**  I have been compiling the less files to the `dist` directory, but would prefer them to compile into the top level `css` and `js` directories.  Didn't have a chance to figure out how to get Grunt to do that yet.  Once that's the case, all we need are the Grunt files and `less` directory.

**Comment by queryluke** [comment]
using the post-commit is slightly over my git knowledge, but seems straight forward. So if someone wants to set that up, feel free. The other option is just merging manually, which isn't ideal.

In terms of the next steps for using gh-pages and developing locally:

## Changes for the repo

**[EDIT]**
1. Merge issue#3 with master and gh-pages (fyi it will remove the prototype/docs directory)
2. Test that gh-pages is working
(Note on edit: I just pushed issue 3 which has a new structure for handling data/header/footer. Might as well use this structure. I've removed the gh-pages-future branch)

## Changes in local development
1. [Install Jekyll](https://help.github.com/articles/using-jekyll-with-pages/#installing-jekyll)
2. NOTE: Skip step 3. I've just pushed the Gemfile & Gemfile.lock into the repo, so once merged they should move with the master branch (no reason for them not to...)
3. when you're ready to develop, in terminal,  navigate to your local repo and run `bundle exec jekyll serve`
4. The site is found at http://localhost:4000

## Site pages

There is a lot of customization options, but for the time begin, I've merely put the header (excluding the jumbotron) and footer into a layout. So create a new html file and put this at the top

```
---
layout: default
title: the-title-of-you-page
---
```

Then just write html like normal. If you need to add info to the header or footer, those are found _layouts/default.html

**Comment by starsplatter** [comment]
I'm interested in learning about the post-commit so I'll make an issue and assign it to me unless someone else would like it. It sounds like you can keep moving forward on the rest of the template work without it until I figure it out?

**Comment by queryluke** [comment]
I've been experimenting with templates. For speakers and schedule, I think we can store the data in .yml files. See my issue#3 branch. _data has event.yml + people.yml which jekyll can access. 

Anyway. For you all, just keep stubbing/creating pages in pure html/css. When we have something we like, i'll covert the files to jekyll friendly formats.

**Comment by sdellis** [comment]
@roastduckalamode Sorry, I was moving over the past few days and also had a few work emergencies... I tested everything out and it works great, except the image is not bleeding to the edge anymore.  Was that intentional?  I'm going to move your Jekyll setup instructions into a wiki page to get it out of this issue.  Cool?

**Comment by queryluke** [comment]
@sdellis That was not intentional. Is it something in my timeline-style.css file? If you see the issue feel free to correct yourself, or just let me know what I need to fix.

Jekyll setup on the wiki page is fine with me, and they can email me directly with any questions.

**Comment by sdellis** [comment]
@roastduckalamode Ok, yes I discovered the problem and was able to correct it by adding a "class" variable at the top of each page.  This would add a class to the section (if the variable exists) allowing one to add custom padding to each page.  If no class variable is added it will just bleed to the edges like the home page.  This may not be a permanent solution, but it should work fine for now.  Going to close this out.
