### ISSUE TITLE
Pinterest style porposal view

### ISSUE THREAD

**Issue by queryluke** [code4lib/2016.code4lib.org#144]
I took a stab at this in the [pinterest-esque...](https://github.com/code4lib/2016.code4lib.org/tree/pinterest-esque-proposal-view) branch. If we like, I'll merge this with master.

Note there are 2 widths which you can view at /proposed-talks.html and proposed-talks-fluid.html

Feedback welcome!

**Comment by bibliotechy** [comment]
I prefer the wider fluid layout. In the non-fluid layout, I feel like the columns are too thin and it makes it a little hard to read. Either way, the boxes all need white background for legibility, because the text is kind of hard to read on the pink background.

Also, since all of this is going to get loaded into the voting machine for next week, not really sure why we'd switch this around at this point. 

I like the layout, as we do get more on the screen, but I find it hard to read them sequentially in this kind of format. You expand the first one, scroll down to read it all, then you have to scroll back up read the second one. 

my (:dollar: \* .02)

**Comment by queryluke** [comment]
@bibliotechy We got an email requesting a usability improvement to these pages.
`It's pretty nifty, but initially she didn't realize they were links to extracts and then when she hovered she thought they were links she could open in other tabs and tried, unsuccessfully. Would it be possible to add a downward/sideways triangle or chevron like many sites do to connote expanding? And possibly the text "Expand" hidden or visible so that screenreaders could use it?`

Shaun proposed a pinterest style layout instead of collapsible divs. 

I didn't realize these would get loaded so quickly. I agree that there is no point to change it. We'll update the "view proposals" link to "vote 4 proposals" next week and take these pages down. 

Ah well, if anything, future code4libconf sites can see this issue and now they've got the code to execute whichever they prefer.
