### ISSUE TITLE
Only first presenter shows for workshop descriptions

### ISSUE THREAD

**Issue by hackartisan** [code4lib/2016.code4lib.org#166]
People have therefore been hacking the form to put all the presenter names in the 'first presenter' field. Currently I don't really see a problem with this, but wanted to put it out there just in case.

**Comment by sdellis** [comment]
I didn't realize that we were only showing a single presenter. At any rate, this should probably be cleaned up in the spreadsheet (after voting?) as it's going to affect our ability to use the "two table" method of presenting speakers and talks/workshops.  We were going to ask speakers to add their bio info after voting, right?

**Comment by hackartisan** [comment]
Yes, we're planning to send a new form with all the 'profile' info y'all wanted along with our confirmation emails. That should match on email, right?

I'm actually looking at the submissions now and not seeing any instances of this hacking that was reported :) Regardless, we will want to display all presenters along with each workshop. I assume that's part of the data crosswalking script? Don't know much about how that works or how trivial it is to add in these other columns, probably want to accumulate them into a single string for display. Then once we have the profiles, each name should link to its profile based on email address.

**Comment by sdellis** [comment]
Ah, ok, so we don't have to do any cleanup after all!  We just need to make sure the profiles for each talk are submitted to the same talk id.  It may make sense to send your form to @roastduckalamode or me to test before sending to the selected workshops? Same with the program committee.

**Comment by hackartisan** [comment]
Well, we need to do 2 things:
1. Display all the presenter names on the site
2. Link workshops&talks to profiles by email. Bi-directional linking may be an issue?

We'll be working from the 'speakers' form in https://github.com/code4lib/2016.code4lib.org/issues/75#issuecomment-141982890

**Comment by hackartisan** [comment]
I see, using the talk ID would be a way around the bidirectional linking problem. But the same person may (and likely will) be giving multiple talks or workshops. I think that's why we were going to use email.

**Comment by queryluke** [comment]
It looks like the "hacks" were on the proposed **talks** form because that one didn't have additional slots co-speakers. It's not a huge deal, but will require some additional data entry on their part to split those into separate columns and get emails for the other speakers. Or, just open up the Google Sheet when voting is over and let the speakers enter their own data. Live and Learn!

@hackmastera, I think you're right. Email will be a better key than name or presentation ID. As long as the final preconference workshop Sheet and speaker bio Sheet share a value, I can connect the dots. 

So you won't need the select input of presentation titles on the form. So long as the presenter enters the same email that they used when submitting the workshop proposal.

**Comment by queryluke** [comment]
I've updated fromSheetsToJekyll, there are multiple options when creating a yaml data file or template (aka post)
1. You can slugify the value (useful to normalize the data. Strips out non-alphanumeric chars and replaces with dashes)
2. You can "hash" the value. It's not a true hash, but it creates a unique key. So we can hash the speaker emails as the primary key.
