### ISSUE TITLE
Schedule page images are missing

### ISSUE THREAD

**Issue by sdellis** [code4lib/2016.code4lib.org#18]
Absolute paths should be made relevant... won't matter when we go to 2016.code4lib.org but right now it's breaking with this url: http://code4lib.github.io/2016.code4lib.org/schedule.html

**Comment by queryluke** [comment]
Looking into other options now

**Comment by queryluke** [comment]
Edit: So in my issue#3.1 branch I started turning the presentations into _posts. Rather than keep them in a _data file. The benefit is that it would allow for additional contributes to create content in a standardized format. But it's not required.

Either way, the problem with using _posts/\* content is the relative urls, event with the DNS update we'd run into the same issue. I have seen some workarounds if the solution below doesn't work. I'll have a commit to issue#18 shortly that should have this solution in place.
1. Create _data/path.yml with content '/2016.code4lib.org/'
2. gitignore the file
3. Add to the wiki a step of creating or changing the file content to '/'
4. When you want to include an absolute path you'd use the jekyll markup {{ site.data.path }} [relative/path/to/file]

Then, when we get our DNS, we can just revert the path.yml content to '/' or remove it at all the {{ site.data.path }} references

**Comment by queryluke** [comment]
@sdellis, issue#18 is in place. If you want to set up a time to pull into the master/gh-pages branch for testing/debugging, let me know.

**Comment by sdellis** [comment]
@roastduckalamode Thanks for all your great work on this!  So, issue #18 pull request was merged a couple of weeks ago.  I'm having problems merging the issue #3.1.  I'm having a bit of a hard time determining what exactly is in 3.1 (in addition to the relative path work) and whether you can help me merge the additional work?  In short, can we close this issue?

**Comment by queryluke** [comment]
@sdellis I merged 3.1 locally and synced it. #3.1 was just more stubbing of issue#3 (the schedule pages). So this can be closed out.
