### ISSUE TITLE
problem with filtered results when using browser 'back' button

### ISSUE THREAD

**Issue by hackartisan** [code4lib/2016.code4lib.org#239]
It's a small bug and fine to wontfix but in case reporting it jogs something in someone's head, here's where happens (Using chrome):
- View the workshops page.
- limit by location.
- view details for one workshop
- use 'back' button
  *\* expected: return to filtered results
  *\* actual: return to all results
  *\* given above, expected: location drop-down should say 'all locations'
  *\* actual: location drop-down displays previous filter. Re-selecting that filter has no effect. I must select a different filter, then re-select the desired filter to see the desired results.

**Comment by queryluke** [comment]
I'll be working on the schedule pages this weekend, so I'll take a look at this as well.

**Comment by sdellis** [comment]
@roastduckalamode I would recommend simply using the Bootstrap Modal (already available) to show the "detail" workshop view. Otherwise you'd have to deal with the History API, cookies, or get into the weeds with a mini single-page webapp.  The only issue then would be if someone wanted to link directly to the detail view.  This could be handled with anchor tags (and a javascript behavior triggered by the anchor to open the modal). @hackmastera we don't have the advantage of server-side filtering... would that solution satisfy your expectations?  (Cookies could be a simple way to handle it too, providing the user has cookies enabled.)  Other thoughts?

**Comment by queryluke** [comment]
@sdellis @hackmastera,

Seems like the disconnect isn't that we need to return to a filtered set, but that when you DO return to the workshops page, a filter is already selected. So the quickest fix might be to add "selected" to the All Locations <option>. I'll try that first.

Luke

**Comment by hackartisan** [comment]
@roastduckalamode That seems totally fine. Definitely go with the simplest fix possible!

**Comment by queryluke** [comment]
Turned out to be a super simple fix, now the back button does filter results.
