### ISSUE TITLE
add times to workshops info

### ISSUE THREAD

**Issue by cmharlow** [code4lib/2016.code4lib.org#279]
Would it be possible to add more granular time information to the Workshops/Preconferences information? Whether it is added to the schedule overview or to each session (instead of just AM/PM), doesn't matter - whatever is easiest and more visible.

AM = 9-12, PM = 1:30-4:30, Full day is 9-4:30 with lunch break

Thanks!

**Comment by queryluke** [comment]
@sdellis @hackmastera I added the times. The full day workshop times wrap a bit odd because I have the link "(w/ lunch break)".

See:
http://2016.code4lib.org/workshops/Code4Arc

I can remove the line or add some css to try and make that text smaller. Thoughts?

Oh, and I just realized, @hackmastera, did you mean you wanted the information on the [workshop page](http://2016.code4lib.org/workshops/) as well?

**Comment by cmharlow** [comment]
Doesn't matter re:odd wrap to me - we can remove lunch break if you like, just wanted to get those times up there as I've gotten a number of questions about it re:folks planning travel around preconf times.

Would also be helpful to get the times listed in the Workshop text here, if possible: http://2016.code4lib.org/schedule/ Can make PR for that page if desired, but wanted to leave content/design decisions to you guys.

**Comment by queryluke** [comment]
I added the times to the workshop index page
