### ISSUE TITLE
Header and Footer links should point to the correct pages

### ISSUE THREAD

**Issue by sdellis** [code4lib/2016.code4lib.org#29]
Remove the "#" and replace with actual links.

**Comment by phette23** [comment]
For the "Conduct" footer link, do we just want to link to [the code](https://github.com/code4lib/antiharassment-policy/blob/master/code_of_conduct.md) on GitHub or are we creating a new page for it? I'm a little hesitant to duplicate a living document like the code onto the site because then we might forget to migrate updates; on the other hand, linking out to a Markdown document on GitHub seems a little jarring for the user.

Once we know what we're doing with the code, the only other footer link to be finalized is "Attend". I'm guessing that'll be like an Eventbrite link or something when tickets go on sale?

**Comment by cdmo** [comment]
I say link to the github page.  It's written in markdown, but renders
fine.  Plus it lets people know a lot more information about the document
and gives the implication that they too can add/modify it.

**Comment by cdmo** [comment]
you know, I think I responded to quickly.  the conduct link is in the footer _and_ the header, and in general I don't like external links in main menus.  perhaps we should create a short page with a summary for the code of conduct and a link to the full repo? 

I'd be happy to make that an issue, own it, and send in the pull request if that sounds cool?

**Comment by queryluke** [comment]
@cdmo I was looking through jekyll docs to see if there was anything native that's similar to file_get_contents. It would be nice to be able to just harvest this content. But it's a no-go without plugins. Additionally, this is a template, so we'd have to fill in the bottom section.

Jekyll supports markdown, so I say instead of a summery, just copy and paste the .md file. Maybe comment out the "If an incident occurs" section until we can get the correct contact info. And additionally link to the repo.

It's not edited too often, and even if it is, just a matter of c/p again.

What do you think? Or a summary is fine too :smile:

**Comment by cdmo** [comment]
@roastduckalamode yeah, I guess I'm not feeling passionately one way or the other.  Here's one way for the "Summary" approach:

"Code4Lib seeks to provide a welcoming, fun, and safe community and conference experience and ongoing community for everyone. We do not tolerate harassment in any form. Discriminatory language and imagery (including sexual) is not appropriate for any event venue, including talks, or any community channel such as the chatroom or mailing list.

Harassment is understood as any behavior that threatens another person or group, or produces an unsafe environment. It includes offensive verbal comments or non-verbal expressions related to gender, gender identity, gender expression, sexual orientation, disability, physical appearance, body size, race, age, religious beliefs, sexual or discriminatory images in public spaces (including online), deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention.

[Read and contribute to our full Code of Conduct document on GitHub](https://github.com/code4lib/antiharassment-policy/blob/master/code_of_conduct.md)"

If we do the summary approach or the full document, we'll have to keep it relatively up-to-date either way.  So... yeah.. let's do one of these things :wink:

**Comment by sdellis** [comment]
Sorry, I was out all last week and completely unplugged.  Just catching up now.  

There is one more option, and that would be to create a Jekyll site that would publish this as a simple HTML doc (with current contact as a yml datafile) and allow us to simply embed it in an iframe in the site.  We would need to make sure that changes to the policy resulted in generating a new gh-pages policy site.  Any of these options would work, but the challenges to staying in sync are about equal with all of them.

**Comment by queryluke** [comment]
IMHO
1. the CoC repo is a template file that gets updated in-between conferences.
2. People should know-about/agree-to the CoC when registering (so we need it finalized by then)
3. We shouldn't change the CoC between registration and the end of the conference. This just seems legally logical to me (but I'm not a lawyer)
4. Thus, a simple copy and paste of the markdown & merge the day before registration should suffice
5. And we get the benefits of having our css in place (as opposed to an iframe)

Charlie's summary is sufficiently accurate and highlights the fact that people can contribute. So, for the time being, let's use Charlie's summary, and when registration comes around, we can insert the fill-in-the-blank sections and put the full document on the site.

**Comment by cdmo** [comment]
Good points to think about the registrant and what they can/should expect.

**Comment by sdellis** [comment]
Hmm... yeah, I don't think we have any policy on changing policies, but I
will bring it up in the LPC meeting tomorrow.  We are working on a "Refund
Policy" now, and should probably at the very least state whether policies
can change.

But I agree with going with Charlie's solution for now.
