### ISSUE TITLE
Break start/stop times need to be updated

### ISSUE THREAD

**Issue by dlacy** [code4lib/2016.code4lib.org#330]
We played with the breaks a little to make room for announcements and raffles. The final schedule is here:

https://docs.google.com/document/d/1T88F-qSmKqcJ3oSor6a10XKXDfMPE6rV4eJ8gIrjDXs/edit

**Comment by sdellis** [comment]
I will update this.

**Comment by queryluke** [comment]
Let me know if you need help. I'll be available after 7 tonight

**Comment by sdellis** [comment]
Ok, I was actually going to post menus and split up the venues (adding floorplans, etc), so @roastduckalamode that would be awesome. I have to go pick up my kids and make them some dinner... but will be online later tonight.  

I think the blue print on the schedule is for internal use only, @dlacy ?  Although it would be nice to say "Giveaways" or "Door Prizes" instead of "Housekeeping" as a title to let folks know that they need to be "in it to win it" (I will add "must be present" to our policies).  

One question for @dlacy re: schedule ... Is this correct for Day 1? 30 second announcement?

> 14:30-14:30 - Pre-Break Announcement
> Lightning talk signups for Wednesday Morning
> Announce breakout session topics and locations
> Load lightning talk slides onto computer

**Comment by dlacy** [comment]
@roastduckalamode @sdellis 
Ignore all details for announcements and breaks, just put "Break" or "Announcements" where appropriate. You can also ignore all of the "Pre-Break Announcement" declarations. Those are for internal use only. The "Pre-break announcements" are quickies, so that's why they don't take any time.

**Comment by bibliotechy** [comment]
@sdellis @roastduckalamode if there are discreet things I could work on, let me know. I'm free tonight

**Comment by queryluke** [comment]
Sorry guys. I'll have to get to this tomorrow morning. Just got out of
urgent care with a torn ligament in my ankle.

**Comment by bibliotechy** [comment]
@roastduckalamode oh noes. :crying_cat_face:

**Comment by queryluke** [comment]
finished this up. I left everything as annoucements. If you want to change the titles to giveaways where appropriate, it's just a matter of editing the _data/schedule.yml file.

**Comment by dlacy** [comment]
I like "Announcements".
